import { Injectable } from '@angular/core';

export type Category = {
  type: 'category';
  name: string;
};

export type Product = {
  type: 'product';
  name: string;
  mrp: number;
  discount: number;
  requirement: string;
  finaleprice: string;
};

export type ProductType = Category | Product;

@Injectable({
  providedIn: 'root',
})
export class Master {
  masterProducts: ProductType[] = [
    { "type": "category", "name": "SPARKLERS" },
    { "type": "product", "name": "7 cm Electric Sparklers", "mrp": 20, "discount": 10, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "7 cm Colour Sparklers", "mrp": 24, "discount": 12, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "12 cm Colour Sparklers", "mrp": 56, "discount": 28, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "12 cm Green Sparklers", "mrp": 60, "discount": 30, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "12 cm Red Sparklers", "mrp": 60, "discount": 30, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "15 cm Electric Sparklers", "mrp": 80, "discount": 40, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "15 cm Colour Sparklers", "mrp": 90, "discount": 45, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "15 cm Green Sparklers", "mrp": 100, "discount": 50, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "15 cm Red Sparklers", "mrp": 110, "discount": 55, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "30 cm Electric Sparklers (5 pcs)", "mrp": 80, "discount": 40, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "30 cm Colour Sparklers (5 pcs)", "mrp": 90, "discount": 45, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "30 cm Green Sparklers (5 pcs)", "mrp": 100, "discount": 50, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "30 cm Red Sparklers (5 pcs)", "mrp": 110, "discount": 55, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "50 cm Electric Sparklers", "mrp": 340, "discount": 170, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "50 cm Colour Sparklers", "mrp": 400, "discount": 200, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "50 cm Multi Mix", "mrp": 480, "discount": 240, "requirement": "", "finaleprice": "0" },
    
    { "type": "category", "name": "2025 PREMIUM" },
    { "type": "product", "name": "10 cm Jazzy Violet", "mrp": 100, "discount": 50, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "10 cm Bloom Pink", "mrp": 100, "discount": 50, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "15 cm Jazzy Violet", "mrp": 160, "discount": 80, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "15 cm Scarlet Orange", "mrp": 160, "discount": 80, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "15 cm Bloom Pink", "mrp": 200, "discount": 100, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "15 cm Super Mix", "mrp": 200, "discount": 100, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "30 cm Super Mix", "mrp": 240, "discount": 120, "requirement": "", "finaleprice": "0" },
    
    { "type": "category", "name": "FLOWER POTS" },
    { "type": "product", "name": "Flower Pots Big", "mrp": 140, "discount": 70, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Flower Pots Special", "mrp": 170, "discount": 85, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Flower Pots Ashoka (Giant)", "mrp": 240, "discount": 120, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Colour Koti", "mrp": 360, "discount": 180, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Colour Koti Premium", "mrp": 440, "discount": 220, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Colour Koti Giant", "mrp": 440, "discount": 220, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Colour Koti Deluxe Premium", "mrp": 640, "discount": 320, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Flower Pot Deluxe (5pcs)", "mrp": 300, "discount": 150, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Colour Cone Pink (Varshini brand)", "mrp": 840, "discount": 420, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Red Koti Deluxe", "mrp": 640, "discount": 320, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Green Berry (Sonny)", "mrp": 1200, "discount": 600, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Colour Koti XL", "mrp": 400, "discount": 200, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Colour Cone Mega", "mrp": 600, "discount": 300, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Dazzling Pots (Kali's Brand)", "mrp": 700, "discount": 350, "requirement": "", "finaleprice": "0" },
    
    { "type": "category", "name": "GUJARAT SPECIAL GIANT MUD POTS" },
    { "type": "product", "name": "Tim Tim (Ko-ko) 5pcs", "mrp": 400, "discount": 200, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "2 in 1 Ashoka (10 pcs)", "mrp": 700, "discount": 350, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Colour Changing Bada (5pcs)", "mrp": 800, "discount": 400, "requirement": "", "finaleprice": "0" },
    
    { "type": "category", "name": "GROUND CHAKKARS" },
    { "type": "product", "name": "Ground Chakkar Big", "mrp": 120, "discount": 60, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Ground Chakkar Special", "mrp": 180, "discount": 90, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Ground Chakkar Deluxe", "mrp": 280, "discount": 140, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Spinner Mega Deluxe (Vanitha Brand)", "mrp": 500, "discount": 250, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Plastic Spinner (Liya Brand)", "mrp": 360, "discount": 180, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Plastic Spinner Deluxe (Liya Brand)", "mrp": 420, "discount": 210, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Fortune Chakkar", "mrp": 440, "discount": 220, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Disco Wheel", "mrp": 160, "discount": 80, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Colour Spinner Mix", "mrp": 400, "discount": 200, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Whistling Wheel", "mrp": 360, "discount": 180, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Cocktail Spinner (Ayyan Brand)", "mrp": 160, "discount": 80, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Disco Multi (Pink and orange) Ayyan brand", "mrp": 440, "discount": 220, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Zodiac Jumping Chakkar (Ayyan Brand)", "mrp": 440, "discount": 220, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "90CC (Red and green) Starwell Brand", "mrp": 360, "discount": 180, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Ground Spin Ashoka (Extra Power Ashok Brand)", "mrp": 360, "discount": 180, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Ground Spin Deluxe (extra timing Ashok Brand)", "mrp": 440, "discount": 220, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Lotus Spinner (Firefly) 3pcs", "mrp": 260, "discount": 130, "requirement": "", "finaleprice": "0" },
    
    { "type": "category", "name": "TORCHES (FIRESTICKS)" },
    { "type": "product", "name": "Lollipop Stick (5pcs) 1 min per stick", "mrp": 500, "discount": 250, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Ultra Ben Ten (3pcs)", "mrp": 240, "discount": 120, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Night Light (3 pcs) Vanitha Brand", "mrp": 300, "discount": 150, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Japan Burger", "mrp": 360, "discount": 180, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Yo Yo Bada Candle", "mrp": 400, "discount": 200, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Selfie Stick (5 pcs)", "mrp": 400, "discount": 200, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Navaranga Multicolour (5 pcs)", "mrp": 360, "discount": 180, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Wonderla Candle (3 pcs)", "mrp": 320, "discount": 160, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Whistling Sticks (5 pcs)", "mrp": 360, "discount": 180, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Sivakasi Special Candle", "mrp": 360, "discount": 180, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Magic Wand (3 pcs) full crackling", "mrp": 480, "discount": 240, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Onward City Mega (3 pcs) Green Crackling", "mrp": 400, "discount": 200, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Crackling Gun Mini (5 pcs) Colour with Smoke", "mrp": 440, "discount": 220, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Crackling Gun Big (2 pcs)", "mrp": 500, "discount": 250, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Waterfalls Candle (5 pcs)", "mrp": 400, "discount": 200, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Jelly Bean Pencil (3 pcs)", "mrp": 280, "discount": 140, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Trix Mix Mega (3 pcs) Red and Green Crackling", "mrp": 400, "discount": 200, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Rainbow Colour Smoke (3 Pcs)", "mrp": 320, "discount": 160, "requirement": "", "finaleprice": "0" },
    
    { "type": "category", "name": "TWINKLING STARS" },
    { "type": "product", "name": "46 cm Twinkling Star", "mrp": 60, "discount": 30, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "120 cm Twinkling star", "mrp": 140, "discount": 70, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Mickey Rope Multi Colour (2mins timing per rope)", "mrp": 400, "discount": 200, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Colour Striw Rope (Legend Brand)", "mrp": 400, "discount": 200, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Vanitha Rope Pink (4 mins per rope)", "mrp": 500, "discount": 250, "requirement": "", "finaleprice": "0" },
    
    { "type": "category", "name": "CHILDREN'S SPECIALS" },
    { "type": "product", "name": "Magic Stone Green", "mrp": 40, "discount": 20, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Anaconda Tablets", "mrp": 40, "discount": 20, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Snake Balls Big (Sonny)", "mrp": 100, "discount": 50, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Magic Stone", "mrp": 60, "discount": 30, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Kitkat (Crackling)", "mrp": 80, "discount": 40, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Photo Flash", "mrp": 200, "discount": 100, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Butterfly Multicolour", "mrp": 280, "discount": 140, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Bambara Spinner (Iniya's Brand)", "mrp": 320, "discount": 160, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Helicopter (Drone) (Iniya's Brand)", "mrp": 320, "discount": 160, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Siren Mini (5pcs) (Iniya's Brand)", "mrp": 400, "discount": 200, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Siren Mega (2pcs)(Iniya's Brand)", "mrp": 280, "discount": 140, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Siren Mega (3 pcs) (Iniya's Brand)", "mrp": 440, "discount": 220, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Pop Pop (Smokeless)", "mrp": 40, "discount": 20, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Money in the bank mini (3 pcs)", "mrp": 400, "discount": 200, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Magic Show Bada Money in the Bank (2 pcs)", "mrp": 500, "discount": 250, "requirement": "", "finaleprice": "0" },
    
    { "type": "category", "name": "TRENDY PEACOCK" },
    { "type": "product", "name": "Mini Peacock", "mrp": 360, "discount": 180, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Medium Peacock (5 eyes) Starwell Brand", "mrp": 440, "discount": 220, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Medium Peacock Crackling (3 eyes)", "mrp": 400, "discount": 200, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Budget Bad Peacock (5 eyes)", "mrp": 720, "discount": 360, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Bada Red and Green Crackling (Amman Brand)", "mrp": 800, "discount": 400, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Bada Extreme Display (Suryakala)", "mrp": 1000, "discount": 500, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "2 in 1 Function (Wowstar Brand)", "mrp": 1100, "discount": 550, "requirement": "", "finaleprice": "0" },
    
    { "type": "category", "name": "FOUNTAINS" },
    { "type": "product", "name": "Winner Multicolour (5 pcs)", "mrp": 220, "discount": 110, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Tank Fountain (Vetri Brand) (5 pcs)", "mrp": 320, "discount": 160, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Touch and Touch Mini Queen (5 pcs)", "mrp": 240, "discount": 120, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "1000K Sizzling (2 pcs)", "mrp": 360, "discount": 180, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Amarnath Fountain (5 pcs)", "mrp": 280, "discount": 140, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Pop It Crackling (3 pcs) 45 secs per piece", "mrp": 360, "discount": 180, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "3 in 1 Triple Fountain", "mrp": 500, "discount": 250, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Asrafi Mini (5 pcs)", "mrp": 160, "discount": 80, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Asrafi Small (10 pcs)", "mrp": 200, "discount": 100, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Asrafi Big (5 pcs)", "mrp": 160, "discount": 80, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Asrafi Special (5 pcs)", "mrp": 240, "discount": 120, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Cockfight Red (2 pcs)", "mrp": 400, "discount": 200, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Fanta Shiny (Signature Product)", "mrp": 560, "discount": 280, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Lollipop (2 pcs)", "mrp": 400, "discount": 200, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Bingo Music With Multicolour", "mrp": 360, "discount": 180, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Fountain with Skyshot (4 varieties)", "mrp": 400, "discount": 200, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Tricolour Bada (5 pcs)", "mrp": 560, "discount": 280, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "5 Girls 3'' (5 varieties)", "mrp": 440, "discount": 220, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Angry Bird (5 varieties)", "mrp": 440, "discount": 220, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Tower Pot (30 secs fountain with 2 skyshots)", "mrp": 800, "discount": 400, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Violet Matrix (40 secs fountain with 2 skyshots)", "mrp": 900, "discount": 450, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "5 Different 2½ '' fountain (5 pcs) Karpagaraja Brand", "mrp": 260, "discount": 130, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Ammnd Crackling Fountains (3 pcs)", "mrp": 500, "discount": 250, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Bad Boy Mega (3 pcs) Vadivel Brand", "mrp": 800, "discount": 400, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Utsav Crackling Mega Fountain (3 pcs)", "mrp": 800, "discount": 400, "requirement": "", "finaleprice": "0" },
    
    { "type": "category", "name": "MATCHES" },
    { "type": "product", "name": "King 5 in 1", "mrp": 120, "discount": 60, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Prince 10 in 1", "mrp": 300, "discount": 150, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Atlas 5 in 1 Tube", "mrp": 400, "discount": 200, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Robins 5 in 1", "mrp": 300, "discount": 150, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Robins Laptop 10 in 1", "mrp": 500, "discount": 250, "requirement": "", "finaleprice": "0" },
    
    { "type": "category", "name": "BIJILI" },
    { "type": "product", "name": "Red Bijili (100 pcs)", "mrp": 70, "discount": 35, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Striped Bijili (100 pcs)", "mrp": 80, "discount": 40, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Vadakapatti Deluxe Bijili", "mrp": 100, "discount": 50, "requirement": "", "finaleprice": "0" },
    
    { "type": "category", "name": "SOUND CRACKERS" },
    { "type": "product", "name": "2 ¾ Kuruvi", "mrp": 16, "discount": 8, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "2 ¾ Deluxe Kuruvi", "mrp": 20, "discount": 10, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "3 ½ Lakshmi", "mrp": 28, "discount": 14, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "4\" Lakshmi", "mrp": 36, "discount": 18, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "4'' Legend Brand (Machine Fuse)", "mrp": 56, "discount": 28, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "4 ½'' Gold Lakshmi", "mrp": 60, "discount": 30, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "4½ '' Deluxe Lakshmi machine Fuse", "mrp": 70, "discount": 35, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "5\" Deluxe Lakshmi 15 Ply (machine Fuse)", "mrp": 110, "discount": 55, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "6\" Laksmi", "mrp": 120, "discount": 60, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "6\" Lakshmi dlx (Machine Fuse)", "mrp": 130, "discount": 65, "requirement": "", "finaleprice": "0" },
    
    { "type": "category", "name": "PAPER BOMBS (MACHINE FUSE)" },
    { "type": "product", "name": "Avatar 4\" (100 gms)", "mrp": 80, "discount": 40, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Adiyal 5\" Deluxe (150 gms)", "mrp": 100, "discount": 50, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Adiyal 5\" (250 gms)", "mrp": 110, "discount": 55, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Rock 5\" (500 gms)", "mrp": 220, "discount": 110, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Naragasura 12\" (750 gms)", "mrp": 360, "discount": 180, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Hulk 1kg", "mrp": 400, "discount": 200, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Gold Deluxe (1.25kg)", "mrp": 460, "discount": 230, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Bada Deluxe 15\" (2.5 kgs)", "mrp": 840, "discount": 420, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Big Sanal Vedi (5 pcs)", "mrp": 240, "discount": 120, "requirement": "", "finaleprice": "0" },
    
    { "type": "category", "name": "BOMBS" },
    { "type": "product", "name": "Bullet Foils", "mrp": 100, "discount": 50, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Flower Bomb", "mrp": 240, "discount": 140, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "555 Bomb Bada", "mrp": 300, "discount": 150, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Hydro Bomb (m.fuse)", "mrp": 260, "discount": 130, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Classic Bomb", "mrp": 280, "discount": 140, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Coronation Bomb (India's most favourite bomb)", "mrp": 400, "discount": 200, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Agni Bomb", "mrp": 360, "discount": 180, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Dinosaur 3D Bomb", "mrp": 440, "discount": 220, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Digital Bomb", "mrp": 440, "discount": 220, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Thriller Bomb", "mrp": 600, "discount": 300, "requirement": "", "finaleprice": "0" },
    
    { "type": "category", "name": "GIANT AND DELUXE CRACKERS" },
    { "type": "product", "name": "28 Giant crackers", "mrp": 80, "discount": 40, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "56 Giant crackers", "mrp": 160, "discount": 80, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "24 Deluxe Crackers", "mrp": 130, "discount": 65, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "50 Deluxe Crackers", "mrp": 240, "discount": 120, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "100 Deluxe Crackers", "mrp": 480, "discount": 240, "requirement": "", "finaleprice": "0" },
    
    { "type": "category", "name": "WALA FUNCTIONS" },
    { "type": "product", "name": "100 Wala (Brand)", "mrp": 90, "discount": 45, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "200 Wala (Brand)", "mrp": 160, "discount": 80, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "300 Wala (Brand)", "mrp": 240, "discount": 120, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "1000 Wala (Brand full count)", "mrp": 760, "discount": 380, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "2000 Wala (Brand full count)", "mrp": 1440, "discount": 720, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "5000 Wala (Brand full count)", "mrp": 3400, "discount": 1700, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "10000 Wala (Brand full count)", "mrp": 6500, "discount": 3250, "requirement": "", "finaleprice": "0" },
    
    { "type": "category", "name": "OTHERS" },
    { "type": "product", "name": "1K (Half Count)", "mrp": 400, "discount": 200, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "2K (Half count)", "mrp": 800, "discount": 400, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "5K (Half count)", "mrp": 2000, "discount": 1000, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "10K (Half count)", "mrp": 4000, "discount": 2000, "requirement": "", "finaleprice": "0" },
    
    { "type": "category", "name": "DIGITAL WALA" },
    { "type": "product", "name": "Jagajal Bada 100 wala function", "mrp": 60, "discount": 30, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "90 Watts (3 pcs) (Star World brand)", "mrp": 280, "discount": 140, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Magic Wala (5000 function)", "mrp": 300, "discount": 150, "requirement": "", "finaleprice": "0" },
    
    { "type": "category", "name": "MINI ARIEL AND FANCY NIGHT OUTS" },
    { "type": "product", "name": "5 Falls", "mrp": 200, "discount": 100, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "7 Shots (5pcs)", "mrp": 240, "discount": 220, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "7 Shots (10 pcs)", "mrp": 480, "discount": 240, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Skyking Starworld (5 pcs)", "mrp": 320, "discount": 160, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Skyking Storm rise (5pcs)", "mrp": 320, "discount": 160, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Thunder Crackling (5 pcs)", "mrp": 320, "discount": 160, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Red Robo (Mother's Brand) 5 pcs", "mrp": 300, "discount": 150, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Craba Night Sky Shots (10 pcs)", "mrp": 400, "discount": 200, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Lamborghini (10 pcs)", "mrp": 400, "discount": 200, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Dup Tip (5 pcs)", "mrp": 360, "discount": 180, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Penta Celebration (5 pcs)", "mrp": 300, "discount": 150, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Penta Brand (5 pcs)", "mrp": 360, "discount": 180, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Penta Mega (2\" pipe) INF Brand (5 pcs)", "mrp": 600, "discount": 300, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Fly Machine (10 pcs) Clr Fly Chakkars (Vanitha)", "mrp": 1040, "discount": 520, "requirement": "", "finaleprice": "0" },
    
    { "type": "category", "name": "CHOTTA FANCY COLLECTIONS" },
    { "type": "product", "name": "Chotta Fancy", "mrp": 100, "discount": 50, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "The War (3 pcs)", "mrp": 360, "discount": 180, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Sky Angel (3 pcs)", "mrp": 400, "discount": 200, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Sky paint (3 pcs)", "mrp": 400, "discount": 200, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "2\" Single Ariel", "mrp": 160, "discount": 80, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "2\" Ariel ( Blue Star Brand)", "mrp": 220, "discount": 110, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "2\" (3 pcs)", "mrp": 440, "discount": 220, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "2\" (3 pcs) Brand (Vetri)", "mrp": 500, "discount": 250, "requirement": "", "finaleprice": "0" },
    
    { "type": "category", "name": "SKY SHOT EVENTS (ALL BRANDED PRODUCTS)" },
    { "type": "product", "name": "2½\" Ariel (Bluestar and Puma)", "mrp": 400, "discount": 200, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "2½\" Triple Ball (Wowstar Brand)", "mrp": 480, "discount": 240, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "3\" Ariel (Bluestar)", "mrp": 480, "discount": 240, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "3\" Fire Out (Jayaruby's)", "mrp": 440, "discount": 220, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "3\" Double Piece Darbar (Legend Brand)", "mrp": 1200, "discount": 600, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "3\" Triple Ball (2 pcs) Mother's Brand", "mrp": 1100, "discount": 550, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "3½\" Ariel (Pandian, Bluestar, Maan, Sri Selvi Brands)", "mrp": 580, "discount": 290, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "4\" Darbar Crackling Stars", "mrp": 600, "discount": 300, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "4\" Sizzling Display", "mrp": 600, "discount": 300, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "4\" Coconut Tree Crackling", "mrp": 640, "discount": 320, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "4½\" Double Ball (Kathirvelan Brand)", "mrp": 960, "discount": 480, "requirement": "", "finaleprice": "0" },
    
    { "type": "category", "name": "UNIQUE SHELLS WITH TOP BRANDS (SONNY, Balaji's, INF, BLUESTAR, Ajantha)" },
    { "type": "product", "name": "2½\" Drop up series (2 pcs) Sonny", "mrp": 1000, "discount": 500, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "2\" Fantasy 4 in 1 function (2 pcs) Sonny", "mrp": 900, "discount": 450, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "2½\" Euro Series (2 pcs) Sonny", "mrp": 960, "discount": 480, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "2½\" Miami Nights (2 pcs) Sonny", "mrp": 1080, "discount": 540, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "2½\" Blue Pearls (2 pcs) Sonny", "mrp": 1080, "discount": 540, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "2\" (3 pcs) Split Up Sonny", "mrp": 1200, "discount": 600, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "3½\" Mela (2 pcs) Ajantha Brand", "mrp": 2200, "discount": 1100, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "3½\" Spiderman 7 Steps Ajantha Brand", "mrp": 1100, "discount": 550, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Thanos 8 Step Ajantha Brand", "mrp": 1200, "discount": 600, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "3\" Triple Treat 7 Steps (3 pcs) INF Brand", "mrp": 2300, "discount": 1150, "requirement": "", "finaleprice": "0" },
    
    { "type": "category", "name": "HAPPY DIWALI 2025" },
    { "type": "product", "name": "4\" 12 Outs in Single Pipe (Liya Brand)", "mrp": 900, "discount": 450, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "4\" Extreme Display (Pink) God father INF Brand", "mrp": 1100, "discount": 550, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "4\" Extreme Display (Blue) Neela Angels INF Brand", "mrp": 1100, "discount": 550, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "4\" Lavender Choice (Maan Brand)", "mrp": 900, "discount": 450, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "4\" Purple Lover (Maan Brand)", "mrp": 900, "discount": 450, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "4\" Bingo Pink (Bluestar Brand)", "mrp": 800, "discount": 400, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "4\" Blue Sky (Bluestar Brand)", "mrp": 800, "discount": 400, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "4½\" Pure Pink Out (Sri Amman Brand)", "mrp": 960, "discount": 480, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "4½\" Pink and Green Double Display (Sri Amman)", "mrp": 1000, "discount": 500, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "4½\" Pink and Blue Double Ball (Ananda's Brand)", "mrp": 1200, "discount": 600, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "5\" The Sky Pink 3D series (2 pcs) Vanitha Brand", "mrp": 2900, "discount": 1450, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "4½\" Double Pack Series (2 pcs) Suryakala", "mrp": 1700, "discount": 850, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "4\" Magic Crystal (2 pcs) Sonny", "mrp": 2400, "discount": 1200, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "4\" Blue Octopus (2 pcs) Sonny", "mrp": 2400, "discount": 1200, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "4\" Blue Eyes (2 pcs) Sonny", "mrp": 2400, "discount": 1200, "requirement": "", "finaleprice": "0" },
    
    { "type": "category", "name": "MOST WANTED- OUR SIGNATURE PRODUCTS (SONNY, Balaji's Ring Series)" },
    { "type": "product", "name": "5\" Oscar (2 pcs) Extreme Display SONNY", "mrp": 3000, "discount": 1500, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "5\" Zulk War (2 pcs) Crackling Ring SONNY", "mrp": 2800, "discount": 1400, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "5\" Seventh Sense (2 pcs) Blue Ring SONNY", "mrp": 2800, "discount": 1400, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "5\" Hercules (2 pcs) Colourful Sky SONNY", "mrp": 2800, "discount": 1400, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "5\" Monna Series (2 pcs) Superb Display SONNY", "mrp": 2900, "discount": 1450, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "5\" Tina Double Dhamakka (2 pcs) SONNY", "mrp": 2900, "discount": 1450, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "5\" Gamma Crackling in the Sky( 2 pcs) SONNY", "mrp": 2900, "discount": 1450, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "4\" (3 pcs) Surfing (Balaji's Brand)", "mrp": 2200, "discount": 1100, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "4\" (3 pcs) Skydiving (Balaji's Brand)", "mrp": 2200, "discount": 1100, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "4\" (2 pcs) Storm Blast Mega Display", "mrp": 2400, "discount": 1200, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "5\" (3 pcs) Forest Series Balaji's Brand (4 Varieties)", "mrp": 3400, "discount": 1700, "requirement": "", "finaleprice": "0" },
    
    { "type": "category", "name": "MULTISHOTS UNIQUE DISPLAY" },
    { "type": "product", "name": "12 Shot Crackling", "mrp": 300, "discount": 150, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "12 Shot Brand", "mrp": 440, "discount": 220, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "12 Shot Colour", "mrp": 480, "discount": 240, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "30 Shot", "mrp": 960, "discount": 480, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "30 Shot Brand", "mrp": 1040, "discount": 520, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "60 Shot Brand", "mrp": 2000, "discount": 1000, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "120 Shot Brand", "mrp": 4000, "discount": 2000, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "30 Shot Full Crackling (Sri Vijay Brand)", "mrp": 1300, "discount": 650, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "25 Whistling with Blast (SONNY Cocolands)", "mrp": 1700, "discount": 850, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "60 Shot Full Crackling (Bluestar)", "mrp": 3000, "discount": 1500, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "30 Shot Full Whistling (Ramji Brand)", "mrp": 1400, "discount": 700, "requirement": "", "finaleprice": "0" },
    
    { "type": "category", "name": "ROCKETS" },
    { "type": "product", "name": "Bomb Rocket (Puma Brand)", "mrp": 180, "discount": 90, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Lunik Rocket (Bheema Brand)", "mrp": 300, "discount": 150, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Double Sound Rocket", "mrp": 280, "discount": 140, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "Whistling Rocket (Varshini Brand)", "mrp": 320, "discount": 160, "requirement": "", "finaleprice": "0" },
    
    { "type": "category", "name": "GUN AND RING" },
    { "type": "product", "name": "Gun with 5 Rings Combo box (SONNY Brand)", "mrp": 320, "discount": 160, "requirement": "", "finaleprice": "0" },
    
    { "type": "category", "name": "GIFTBOX" },
    { "type": "product", "name": "35 Items", "mrp": 1500, "discount": 750, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "40 Items", "mrp": 1700, "discount": 850, "requirement": "", "finaleprice": "0" },
    { "type": "product", "name": "50 VIP Box", "mrp": 2100, "discount": 1050, "requirement": "", "finaleprice": "0" }
  ]
}
